#!/usr/bin/env bash

APP_ARGS=${@}
CONFUTIL_PATH="${HOME}/.confutil"
CONFS_CURRENT="${CONFUTIL_PATH}/current"
CONFS_AVAILABLE="${CONFUTIL_PATH}/available"

. "${CONFUTIL_PATH}/common.sh"

usage() {
    echo "usage:"
    return 1
}

scripts_load() {
    [ "${1}" != "quiet" ] && einfo "Initializing confutil scripts"

    if [ ! -d "${CONFS_AVAILABLE}" ]; then
        einfo "Creating ${CONFS_AVAILABLE}"
        mkdir -p "${CONFS_AVAILABLE}"
    fi

    if [ ! -d "${CONFS_CURRENT}" ]; then
        einfo "Creating ${CONFS_CURRENT}"
        mkdir -p "${CONFS_CURRENT}"
    fi

    for script in ${CONFS_CURRENT}/*; do
        [ "${1}" != "quiet" ] && einfo "Loading $(basename ${script})"
        source "${script}" "${CONFUTIL_PATH}"
    done
}

scripts_list() {
    echo "Available scripts:"
    for script in ${CONFS_AVAILABLE}/*; do
        s=$(basename ${script})
        _ISCHOICE=" "
        _CHOICE=""
        _ENABLED_CLR="\033[1;31m"
        _ENABLED="off"

        if [ -d "${CONFS_AVAILABLE}/${s}" ]; then
            _ISCHOICE="\033[0;36mc\033[0m"
            if [ -L "${CONFS_CURRENT}/${s}" ]; then
                _CHOICE="$(basename $(readlink "${CONFS_CURRENT}/${s}"))"
                _ENABLED_CLR="\033[1;32m"
                _ENABLED="on"
            fi
        else
            if [[ $(readlink "${CONFS_CURRENT}/${s}") == "${script}" ]]; then
                _ENABLED_CLR="\033[1;32m"
                _ENABLED="on"
            fi
        fi

        printf "  ${_ISCHOICE} %-16s  ${_ENABLED_CLR}%-3s\033[0m  \033[1;36m%-8s\033[0m\n" "${s}" "${_ENABLED}" "${_CHOICE}"
    done
}

scripts_reload() {
    exec "${SHELL}"
}

script_set() {
    if [ ! -n "${2}" ]; then
        echo "usage: set <script> <choice>"
        return 1
    fi

    if [ ! -e "${CONFS_AVAILABLE}/${1}" ]; then
        eerr "Script '${1}' doesn't exists!"
        return 1
    fi

    if [ ! -d "${CONFS_AVAILABLE}/${1}" ]; then
        eerr "Script '${1}' doesn't have choices!"
        return 1
    fi

    if [ ! -f "${CONFS_AVAILABLE}/${1}/${2}" ]; then
        eerr "Script '${1}' doesn't have choice '${2}'!"
        return 1
    fi

    einfo "Setting choice for '${1}': \033[1;36m${2}\033[0m"
    ln -sf "${CONFS_AVAILABLE}/${1}/${2}" "${CONFS_CURRENT}/${1}"
}

script_enable() {
    if [ -d "${CONFS_AVAILABLE}/${1}" ]; then
        ewarn "Script '${1}' have multiple choices"
        ewarn "Use 'set' to select correct script"
        return 1
    fi

    if [ ! -e "${CONFS_AVAILABLE}/${1}" ]; then
        eerr "Script '${1}' doesn't exists!"
        return 1
    fi

    if [[ $(readlink "${CONFS_CURRENT}/${1}") == "${CONFS_AVAILABLE}/${1}" ]]; then
        ewarn "Script '${1}' already enabled"
        return 1
    fi

    einfo "Enabling ${1}"
    ln -sf "${CONFS_AVAILABLE}/${1}" "${CONFS_CURRENT}/${1}"
}

script_disable() {
    if [ ! -e "${CONFS_CURRENT}/${1}" ]; then
        ewarn "Script ${1} not enabled"
        return 1
    fi

    einfo "Disabling ${1}"
    rm "${CONFS_CURRENT}/${1}"
}

case "${1}" in
    "load")
        scripts_load ${2}
        ;;
    "reload")
        scripts_reload
        ;;
    "list")
        scripts_list
        ;;
    "set")
        script_set ${2} ${3}
        scripts_reload
        ;;
    "enable")
        script_enable ${2}
        scripts_reload
        ;;
    "disable")
        script_disable ${2}
        scripts_reload
        ;;
    *)
        usage
        ;;
esac
