#!/usr/bin/env bash

CONFUTIL_PATH=${1}
. "${CONFUTIL_PATH}/common.sh" $(basename $0)

SSH_ENV="$HOME/.ssh/environment"

# start the ssh-agent
function start_agent {
    # spawn ssh-agent
    einfo "Initializing new SSH agent..."
    ssh-agent | sed 's/^echo/#echo/' > "$SSH_ENV"
    chmod 600 "$SSH_ENV"
    . "$SSH_ENV" > /dev/null
    einfo "$(ssh-add 2>&1)"
}

# test for identities
function test_identities {
    ssh-add -l > /dev/null
    if [ $? -eq 2 ]; then
        start_agent
    fi

    # test whether standard identities have been added to the agent already
    ssh-add -l | grep "The agent has no identities" > /dev/null
    if [ $? -eq 0 ]; then
        einfo "$(ssh-add 2>&1)"
        # $SSH_AUTH_SOCK broken so we start a new proper agent
        if [ $? -eq 2 ]; then
            start_agent
        fi
    fi
}

# check for running ssh-agent with proper $SSH_AGENT_PID
. "${SSH_ENV}"
if [ -n "$SSH_AGENT_PID" ]; then
    ps -ef | grep "$SSH_AGENT_PID" | grep ssh-agent > /dev/null
    if [ $? -eq 0 ]; then
        test_identities
    else
        start_agent
    fi
# if $SSH_AGENT_PID is not properly set, we might be able to load one from
# $SSH_ENV
else
    if [ -f "$SSH_ENV" ]; then
        . "$SSH_ENV" #> /dev/null
    fi
    ps -ef | grep "$SSH_AGENT_PID" | grep ssh-agent > /dev/null
    if [ $? -eq 0 ]; then
        test_identities
    else
        start_agent
    fi
fi
